tbl_note_period_lo:
	.byte $AE		; 00	C1

tbl_note_period_hi:
	.byte $86		; 

	.byte $4E, $86	; 01	C#1
	.byte $F3, $85	; 02	D1
	.byte $9E, $85	; 03	D#1
	.byte $4D, $85	; 04	E1
	.byte $01, $85	; 		F1
	.byte $B9, $84	; 		F#1
	.byte $75, $84	; 		G1
	.byte $35, $84	; 08	G#1
	.byte $F8, $83	; 		A1
	.byte $BF, $83	; 		A#1
	.byte $89, $83	; 		B1
	.byte $57, $83	; 		C2
	.byte $27, $83	; 		C#2
	.byte $F9, $82	; 		D2
	.byte $CF, $82	; 0F	D#2
	.byte $A6, $82	; 10	E2
	.byte $80, $82	; 		F2
	.byte $5C, $82	; 		F#2
	.byte $3A, $82	; 		G2
	.byte $1A, $82	; 		G#2
	.byte $FC, $81	; 		A2
	.byte $DF, $81	; 		A#2
	.byte $C4, $81	; 		B2
	.byte $AB, $81	; 18	C3
	.byte $93, $81	; 
	.byte $7C, $81	; 
	.byte $67, $81	; 
	.byte $52, $81	; 
	.byte $3F, $81	; 
	.byte $2D, $81	; 
	.byte $1C, $81	; 1F
	.byte $0C, $81	; 20
	.byte $FD, $80	; 
	.byte $EE, $80	; 
	.byte $E1, $80	; 
	.byte $D4, $80	; 
	.byte $C8, $80	; 
	.byte $BD, $80	; 
	.byte $B2, $80	; 
	.byte $A8, $80	; 28
	.byte $9F, $80	; 
	.byte $96, $80	; 
	.byte $8D, $80	; 
	.byte $85, $80	; 
	.byte $7E, $80	; 
	.byte $76, $80	; 
	.byte $70, $80	; 2F
	.byte $69, $80	; 30
	.byte $63, $80	; 
	.byte $5E, $80	; 
	.byte $58, $80	; 
	.byte $53, $80	; 
	.byte $4F, $80	; 
	.byte $4A, $80	; 
	.byte $46, $80	; 
	.byte $42, $80	; 38
	.byte $3E, $80	; 
	.byte $3A, $80	; 
	.byte $37, $80	; 
	.byte $34, $80	; 
	.byte $31, $80	; 
	.byte $2E, $80	; 
	.byte $2B, $80	; 3F
	.byte $29, $80	; 40
	.byte $27, $80	; 
	.byte $24, $80	; 
	.byte $22, $80	; 
	.byte $20, $80	; 
	.byte $1E, $80	; 
	.byte $1C, $80  ; 46
	.byte $1B, $80  ; 47: B7 / Noise B
	.byte $00, $F8	; 48 Noise 0
	.byte $01, $F8	; 49 Noise 1
	.byte $02, $F8	; 4A Noise 2
	.byte $03, $F8	; 4B Noise 3
	.byte $0A, $F8	; 4C Noise A
	.byte $04, $F8	; 4D Noise 4
	.byte $05, $F8	; 4E Noise 5
	.byte $06, $F8	; 4F Noise 6
	.byte $07, $F8	; 50 Noise 7
	.byte $08, $F8	; 51 Noise 8
	.byte $09, $F8	; 52 Noise 9
	.byte $0C, $F8	; 53 Noise C
	.byte $0D, $F8	; 54 Noise D
	.byte $0E, $F8	; 55 Noise E
	.byte $0F, $F8	; 56 Noise F
	
	.byte $9B, $F8	; 57 Periodic noise B
	.byte $80, $F8	; 58 Periodic Noise 0
	.byte $81, $F8	; 59 Periodic Noise 1
	.byte $82, $F8	; 5A Periodic Noise 2
	.byte $83, $F8	; 5B Periodic Noise 3
	.byte $8A, $F8	; 5C Periodic Noise A
	.byte $84, $F8	; 5D Periodic Noise 4
	.byte $85, $F8	; 5E Periodic Noise 5
	.byte $86, $F8	; 5F Periodic Noise 6
	.byte $87, $F8	; 60 Periodic Noise 7
	.byte $88, $F8	; 61 Periodic Noise 8
	.byte $89, $F8	; 62 Periodic Noise 9
	.byte $8C, $F8	; 63 Periodic Noise C
	.byte $8D, $F8	; 64 Periodic Noise D
	.byte $8E, $F8	; 65 Periodic Noise E
	.byte $8F, $F8	; 66 Periodic Noise F
