	.byte con_80 
	.byte $F4   ; 
	.byte con_81
	.byte $0C   ; 
;	.byte con_83 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $18   ; 
	.byte $0C   ; 
	.byte $1A   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1A   ; 
	.byte $18   ; 
	.byte $1F   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1F   ; 
	.byte $0C   ; 
	.byte $21   ; 
	.byte $30   ; 
	.byte con_81
	.byte $0C   ; 
;	.byte con_83 
	.byte $24   ; 
	.byte $0C   ; 
	.byte $21   ; 
	.byte $0C   ; 
	.byte $24   ; 
	.byte $0C   ; 
	.byte $26   ; 
	.byte $30   ; 
	.byte con_81
	.byte $0C   ; 
;	.byte con_83 
	.byte $18   ; 
	.byte $0C   ; 
	.byte $21   ; 
	.byte $0C   ; 
	.byte $1F   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte con_81
	.byte $18   ; 
;	.byte con_83 
	.byte $17   ; 
	.byte $0C   ; 
	.byte $18   ; 
	.byte $0C   ; 
	.byte $19   ; 
	.byte $0C   ; 
	.byte $1A   ; 
	.byte $0C   ; 
	.byte $1B   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1D   ; 
	.byte $0C   ; 
	.byte $1E   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $30   ; 
	.byte $18   ; 
	.byte $09   ; 
	.byte con_81
	.byte $03   ; 
;	.byte con_83 
	.byte $18   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $09   ; 
	.byte con_81
	.byte $03   ; 
;	.byte con_83 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1F   ; 
	.byte $09   ; 
	.byte con_81
	.byte $03   ; 
;	.byte con_83 
	.byte $1F   ; 
	.byte $0C   ; 
	.byte $23   ; 
	.byte $09   ; 
	.byte con_81
	.byte $03   ; 
;	.byte con_83 
	.byte $23   ; 
	.byte $0C   ; 
	.byte $21   ; 
	.byte $09   ; 
	.byte con_81
	.byte $03   ; 
;	.byte con_83 
	.byte $21   ; 
	.byte $0C   ; 
	.byte $1F   ; 
	.byte $09   ; 
	.byte con_81
	.byte $03   ; 
;	.byte con_83 
	.byte $1F   ; 
	.byte $0C   ; 
	.byte $21   ; 
	.byte $09   ; 
	.byte con_81
	.byte $03   ; 
;	.byte con_83 
	.byte $21   ; 
	.byte $0C   ; 
	.byte $24   ; 
	.byte $09   ; 
	.byte con_81
	.byte $03   ; 
;	.byte con_83 
	.byte $24   ; 
	.byte $0C   ; 
	.byte $28   ; 
	.byte $30   ; 
	.byte $28   ; 
	.byte $0C   ; 
	.byte $28   ; 
	.byte $0C   ; 
	.byte $28   ; 
	.byte $0C   ; 
	.byte $28   ; 
	.byte $0C   ; 
	.byte con_81
	.byte $0C   ; 
;	.byte con_83 
	.byte $24   ; 
	.byte $0C   ; 
	.byte $24   ; 
	.byte $0C   ; 
	.byte $24   ; 
	.byte $0C   ; 
	.byte $24   ; 
	.byte $0C   ; 
	.byte $23   ; 
	.byte $0C   ; 
	.byte $21   ; 
	.byte $0C   ; 
	.byte $1F   ; 
	.byte $0C   ; 
	.byte $21   ; 
	.byte $18   ; 
	.byte $23   ; 
	.byte $18   ; 
	.byte $21   ; 
	.byte $18   ; 
	.byte $1F   ; 
	.byte $18   ; 
	.byte $1C   ; 
	.byte $24   ; 
	.byte $1F   ; 
	.byte $24   ; 
	.byte $21   ; 
	.byte $18   ; 
	.byte $1F   ; 
	.byte $24   ; 
	.byte $1C   ; 
	.byte $24   ; 
	.byte $21   ; 
	.byte $18   ; 
	.byte $15   ; 
	.byte $18   ; 
	.byte $18   ; 
	.byte $18   ; 
	.byte $1C   ; 
	.byte $18   ; 
	.byte $1F   ; 
	.byte $18   ; 
	.byte con_81
	.byte $0C   ; 
;	.byte con_83 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1A   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $0C   ; 
	.byte $1F   ; 
	.byte $0C   ; 
	.byte $1C   ; 
	.byte $60   ; 
	.byte con_86
